ame: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ginolucianorojo/web-app
        BRANCH=${GITHUB_REF#refs/heads/}
        docker build -t $IMAGE_NAME:$BRANCH .
        docker push $IMAGE_NAME:$BRANCH

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to ECS using AWS CLI
      env:
        ENVIRONMENT_NAME: ${{ github.ref == 'refs/heads/develop' && 'Develop' || 'Testing' }}
      run: |
        CLUSTER_NAME=web-app-cluster
        SERVICE_NAME=web-app-service
        TASK_FAMILY=web-app-task
  
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
        aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME